name: restaurant_app_redux
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  redux: ^5.0.0
  restaurant_domain:
    path: ../restaurant_domain
  restaurant_ui:
    path: ../restaurant_ui

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  surf_lint_rules: ^1.5.0

flutter:
