name: restaurant_ui
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  restaurant_domain:
    path: ../restaurant_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter: